### ISSUE TITLE
Expanding the /pe command

### ISSUE THREAD

**Issue by marcyii** [vyneer/dgg-chat-gui-scripts#1]
So some people still don't use the utilities and still ask for a link manually and so you have to open twitch/ youtube and copy the link from there to post into dgg with /pe.
I would like to wish to directly copy the d.gg url that already has an embed in it and post it with /pe

EXAMPLE:
This is the d.gg url that I want to post directly into chat with /pe

https://www.destiny.gg/bigscreen#twitch/forsen

so that it will show #twitch/forsen in chat.

~ marcyii

**Comment by vyneer** [comment]
If you have an embed open, you can just type "/pe" (with no arguments) and it will post whatever you're watching in chat.

Also I can't change dgg commands from a user script anyway so MMMM.
