### ISSUE TITLE
Add new feature to ignore phrases (with spaces)

### ISSUE THREAD

**Issue by Voiture-0** [vyneer/dgg-chat-gui-scripts#11]
Right now, you can /ignore a word and turn on harsh ignore to stop seeing messages with it in chat like "/ignore AOT" to stop seeing "SOY anyone watch the new AOT? SOY".  However, you can't do this with something that is more than 1 word like "one piece".

This would be nice to have as it lets you have harsh ignore Off, but still be able to ignore messages with specified phrases.

This might work like the custom alert phrases, a text box where you can enter a comma separated list of phrases to be ignored "one piece, league of legends, dungeons and dragons" and is decoupled from the harsh ignore setting.

**Comment by Voiture-0** [comment]
I'll take this on tomorrow

**Comment by vyneer** [comment]
wtf pepeSteer

**Comment by Voiture-0** [comment]
PR created for this: #12

**Comment by vyneer** [comment]
merged #12 so closing this now!
