### ISSUE TITLE
Make a custom settings menu

### ISSUE THREAD

**Issue by vyneer** [vyneer/dgg-chat-gui-scripts#13]
Right now d.gg settings push every checkbox change in settings to the d.gg server, including this addon's. Now, as far as I can tell, this doesn't really hurt anything, but it would still be nice to avoid.

**Comment by RyanMcArthur22** [comment]
I see that currently the DGG utilities settings are within the \<DIV id="chat-settings-form"\>...\</div\>

This leads me to believe that DGG is probably just grabbing all of the inputs within that \<DIV\>

Does it make sense and would it fix the issue to append the DGG utilities settings outside of the \<DIV id="chat-settings-form"\>...\</div\>

Like so:

```
<div class="content nano-content" tabindex="0" style="right: -17px;">
  <div id="chat-settings-form">
    <div class="form-group checkbox">
        <label title="Persistent profile settings">
            <input name="profilesettings" type="checkbox">
            Save settings to profile
        </label>
    </div>
    etc.......
  </div>
  <div id="dgg-utilities-specific-settings">
    <h4>d.gg utilities v1.5.2</h4>
    <div class="form-group checkbox">
        <label>
            <input name="alwaysScrollDown" type="checkbox">
            Always scroll down chat on button press
        </label>
    </div>
    etc....
  </div>
</div>
```

Thoughts?

**Comment by vyneer** [comment]
@RyanMcArthur22 yee, something like that is good, problem is that you gotta create buttons for the menu, logic to open it up when the button is clicked etc.

It's not hard, just don't have much time currently.

**Comment by vyneer** [comment]
Done! #32
