### ISSUE TITLE
Banned phrases doesn't check for paste with mouse right click

### ISSUE THREAD

**Issue by Ricky434** [vyneer/dgg-chat-gui-scripts#19]
The textarea "keyup" event doesn't trigger when you paste with right click, or when you drag the text into the input box. I think it's better to use the "input" event

\- line 824: textarea.addEventListener("keyup", () => { 
\+ line 824: textarea.addEventListener("input", () => {

I don't know how to use issues/pull requests, sorry if this is not the right place :(

**Comment by vyneer** [comment]
You're in the right place for sure, thanks for opening an issue! ❤️

You're prob right that this is better, I'll change it in the dev version when I can, and we'll see if it breaks anything Hhhehehehe

**Comment by vyneer** [comment]
Done! #29
