### ISSUE TITLE
[d.gg utilities] Bot Flair Missing from "Hide Individual Flairs"

### ISSUE THREAD

**Issue by Mojavve** [vyneer/dgg-chat-gui-scripts#22]
[This 'Bot' flair](https://cdn.destiny.gg/2.42.0/flairs/bot.png) is not an option under `Settings -> Hide Individual Flairs`

Here are the options I do see: https://i.imgur.com/bvz8H3R.png

**Comment by Voiture-0** [comment]
Flairs are normally called flair1, flair2, flair3, etc....
Looks like the bot's flair is just called "Bot".
We need to manually add to the list of flairs that is loaded there an item for "Bot".

This is the function that we can change to add "Bot" to: [https://github.com/vyneer/dgg-chat-gui-scripts/blob/main/dgg-utilities.user.js#L984](https://github.com/vyneer/dgg-chat-gui-scripts/blob/main/dgg-utilities.user.js#L984)

**Comment by vyneer** [comment]
Fixed in the dev branch (@Voiture-0 ❤️ PepoTurkey)
