### ISSUE TITLE
suggestion: "soft" custom alert phrases

### ISSUE THREAD

**Issue by shakerrdev** [vyneer/dgg-chat-gui-scripts#38]
I'd like the option to add custom alert phrases that only alert/block enter on an exact match.

example: 

I want to make sure people don't lose their job because of me so I want to alert on wrong nsfw variations (nsf, nswf, etc.). But if I add nsf and sfw I can't type nsfw anymore at all because my message contains nsf and sfw.

**Comment by shakerrdev** [comment]
@vyneer dggL

**Comment by vyneer** [comment]
dggL
