### ISSUE TITLE
Embedded Stream's Chat Feature

### ISSUE THREAD

**Issue by mattroseman** [vyneer/dgg-chat-gui-scripts#41]
This is a script I wrote up to use personally in order to switch DGG chat to the YT chat.
Or, if you're embedding something, you can see the twitch or youtube chat of that stream.

https://gist.github.com/mattroseman/31808b0ee6aeecc72a0e9f2156f95333

I copied your method of using tampermonkey, and when you load it, it adds a button between the chat refresh button and the switch sides button in DGG.

IDK if this is anything you'd be interested in adding to this extension, but I thought I'd offer.
Personally, I like the ability to quickly switch over to check out what the not-DGG chat is saying :)

**Comment by vyneer** [comment]
Seems like a pretty cool idea NODDERS 
Thank you once again :heart:

**Comment by mattroseman** [comment]
Oh, this might not work since my script is injected on the `/bigscreen` page, not the embedded chat.
I add a button in the HTML _around_ the iFrame that is the embedded DGG chat.

So that might cause problems.  😬
