### ISSUE TITLE
Issue with "Stick recent mentions to top of chat"

### ISSUE THREAD

**Issue by realroal** [vyneer/dgg-chat-gui-scripts#42]
As you can see in the images, the mentions feature permanently expands and has previous chat messages hidden underneath new ones. The messages go away once you cant scroll up to see them in chat anymore, but its kind of annoying since it would be a useful feature otherwise. Would be nice if I could just close the pinned mention.

![Capture](https://user-images.githubusercontent.com/113478239/190016196-89caedeb-5aca-48d1-b207-ec5c477ef1e3.JPG)
![Capture1](https://user-images.githubusercontent.com/113478239/190016197-04e0a4da-3213-4454-866f-26897adf927e.JPG)
![Capture2](https://user-images.githubusercontent.com/113478239/190016198-02406c92-1928-4ae9-8564-95efdd5fc55e.JPG)

**Comment by vyneer** [comment]
I feel like it's still a useful feature regardless. I'll think about a close button, but no promises, it might be too obnoxious/ugly or have too much of a performance impact.

You can try the dev version of the script meanwhile, it separates the stacked mentions a bit better.
