### ISSUE TITLE
Lookup YT Stream's Channel Title

### ISSUE THREAD

**Issue by mattroseman** [vyneer/dgg-chat-gui-scripts#48]
It would be a useful feature to lookup a YT stream's channel title so that it can be displayed in the top embeds message.
For example, if someone links an embed to NotSoEurodite's stream, it'll look like `#youtube/jfKfPfyJRdk`, but I'm proposing something like `#youtube/NotSoEurodite`.

I imagine this would require coordination with the backend code to do the actual lookup.

I checked the YouTube API to see if there was an easy enough query to get the title of a YouTube channel from some stream id, and I spun up some quick Python code to test it: [see this Gist](https://gist.github.com/mattroseman/d5575fd598570d27f085b12621555e90).

**Comment by mattroseman** [comment]
If this is something you're interested in adding, I'm interested in helping out. But I don't want to step on your toes.
Let me know if you'd like help :)

**Comment by vyneer** [comment]
Hey there! Yeah, this seems like a good idea :smile: 

I don't think any additional backend memes are necessary, can just use the oEmbed API thing: ```https://www.youtube.com/oembed?url=https%3A//youtube.com/watch%3Fv%3DjfKfPfyJRdk&format=json``` for example

**Comment by mattroseman** [comment]
Wait, is this already a thing? You already have this setup, you just have to edit the settings. Or at least what I was proposing looks like it's already a thing.

[This is the code](https://github.com/vyneer/dgg-chat-gui-scripts/blob/c13660a4c3877c620907234f4a561760d0b414d9/dgg-utilities.user.js#L1194), right?

**Comment by vyneer** [comment]
Oh, I thought you meant changing the text in the "pill":

![image](https://user-images.githubusercontent.com/41237021/194616232-e4ffbe1e-1283-45fc-a825-85bb49a5c446.png)

But if you mean in chat, then yeah :smiley:

**Comment by mattroseman** [comment]
lol, well never mind then.

That's my bad, I didn't see that this was already a thing 😬 

I can look into updating the pill if you'd like though 👍 
Do you think that should match the setting for the youtube embed format, or just always be the channel title?

**Comment by vyneer** [comment]
No worries, my bad for misreading your post as well Hhhehehehe

The pill stuff would be cool, yeah! I think it should be channel name only, since titles can be way too long, would look ugly.

**Comment by vyneer** [comment]
Added with PR #50

:heart:
