### ISSUE TITLE
Embed Links with Violentmonkey broken on chrome again

### ISSUE THREAD

**Issue by Septimius-Severus** [vyneer/dgg-chat-gui-scripts#51]
Hitting the view past embedded links in chat returns no results, even with links posted while chat is loaded up. I'm using: 
Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) 64-bit and the latest versions of both this script and violentmonkey.

**Comment by vyneer** [comment]
Could you post your console logs? Right click -> Inspect -> Console -> Refresh the page.

**Comment by Septimius-Severus** [comment]
Sure, Here you go

`GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT bigscreen:136 
 Unrecognized feature: 'web-share'. bigscreen:136
 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at HTMLDocument.injectScript (d.gg utilities.user.js:271:18)
     injectScript @ d.gg utilities.user.js:271
GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
`
Edit: cleaned log output up a bit, im a moron

**Comment by vyneer** [comment]
Could you try out this version and see if it fixes the issue? https://github.com/vyneer/dgg-chat-gui-scripts/raw/10de9153ecd0206029dd5d4ba58724510dedc2b9/dgg-utilities.user.js

**Comment by Septimius-Severus** [comment]
Yup, it works!

**Comment by vyneer** [comment]
Great! Thanks for reporting the issue :heart: 

Fixed in 9530bae9f688a3653bd3df57af2ffdbbb2807879
