### ISSUE TITLE
Can't connect to vyneer.me on first load

### ISSUE THREAD

**Issue by revelsix** [vyneer/dgg-chat-gui-scripts#54]
The silly little ⚠️ appears when I first load into d.gg chat, it usually goes away after 10+ seconds or after refreshing. I have some funky issues with my DNS that sometimes causes pages not to load on first (second, third, or fourth) attempt that I don't know how to solve so it could very well just be that. Here are the errors it logs to the console :) 
![image](https://user-images.githubusercontent.com/45189851/195723502-4555c6ab-0007-4ef9-8975-7eea32a15b05.png)

Edit: using cloudflare's DNS now, will update if it happens again

**Comment by vyneer** [comment]
Dunno how much I can do here besides changing the wording of the alert so that it's a bit less aggressive :thinking:

**Comment by revelsix** [comment]
yeah i think i'm pretty confident in saying that it was a dns issue because it doesn't show up at all now. thank you verizon for being absolutely awful 👍 i do agree that the wording should still be changed though :)
