### ISSUE TITLE
Include inline-whispers when sticking recent mentions to top

### ISSUE THREAD

**Issue by Voiture-0** [vyneer/dgg-chat-gui-scripts#57]
With the sticky mentions option enabled, in-line whispers should also stick to the top of chat like mentions

**Comment by Voiture-0** [comment]
This should be as simple as adding to the sticky mentions CSS selector to include `.msg-whisper` with the existing `.msg-highlight` target. I'll probably try to do this soon if I find some time.

**Comment by vyneer** [comment]
Added in https://github.com/vyneer/dgg-chat-gui-scripts/commit/ea2b33793947ecc74f9ff163e50f475fc2a4fe12 Pog ❤️
