### ISSUE TITLE
Chat stops sticking to the bottom

### ISSUE THREAD

**Issue by ReFeature** [vyneer/dgg-chat-gui-scripts#63]
![image](https://user-images.githubusercontent.com/26382051/217661637-c0a5b5b7-64bc-424e-b58d-d278c5f78f3d.png)

^ Possibly due to an embed that has multiple lines being posted. Maybe idk

![image](https://user-images.githubusercontent.com/26382051/217661266-260a10bd-9d6f-417d-9262-142cab879e79.png)

I have to Click "More messages below" every time embed is posted.

**Comment by ReFeature** [comment]
maybe it's fixed idk. now it's working fine

**Comment by vyneer** [comment]
Should be fixed in https://github.com/vyneer/dgg-chat-gui-scripts/commit/7ad7ca19e079af1f8e5407b170391401ae44e06a ❤️
