### ISSUE TITLE
Replace Rumble stream ids with titles

### ISSUE THREAD

**Issue by mattroseman** [vyneer/dgg-chat-gui-scripts#68]
I stumbled across what Rumble's oembed URL is and thought I'd share here in case you ever wanted to replace the stream id with the channel name, same as with YT streams.

Rumble's documentation is ass, and I don't think they even give the right root URL for their API or even mention anything about oembed, so this might not be obvious.

`https://rumble.com/api/Media/oembed?url=<the Embed IFrame URL>` is the oembed formula.

**Comment by vyneer** [comment]
Done in 1.8, I think Hhhehehehe
